[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'justmao945/vim-clang'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

